### ISSUE TITLE
Items desapear from inventory after it's finish.

### ISSUE THREAD

**Issue by johnbrasil** [Plajer-Lair/BuildBattle#14]
## Error code

Dont have.
code in ``` tags

Hello man, whats up?

Man, when i configure plugin, and "Register Arena", and when we start arena, when we finish, all itens desapear on my inventory... and the console dont have any error about that.
Some error? 

## Additional info
- Spigot version: Paper 1.13.2
- Plugin version: BuildBattle-4.0.0b-pre-9.jar

**Comment by Plajer** [comment]
enable inventory manager in config
