### ISSUE TITLE
Scoreboard (?)

### ISSUE THREAD

**Issue by iamharak** [Plajer-Lair/BuildBattle#4]
### Sort description of issue
Hello,
We have a problem with the BuildBattle plugin. On our server, we're managing events with commandblocks for years, and with this, we're using the scoreboard a lot. And there is the source of the problem. Let me explain the phenomenon first and then I'll ask: if I put "John" in a scoreboard named "Test", then i write the /eco give @a[team=Test] 1 command in a commandblock, it gives out the prize but after he joins even only in the BuildBattle waiting lobby then quits, the player becomes non-manageable with scoreboards,so if I write in the /eco give @a[Team=Test] 1 command again, I add to the scoreboard vainly, it does not give out the money because it’s not managing the player with the scoreboard he is in. We’ve tried every possible way but we could’nt find a solution for this, why does this happens.I would like to add that a re-login to the server solves it.

The question is the following: What can cause that if a player plays a BuildBattle game, he becomes unmanageable with scoreboards until he re-logins the server? What can the plugin „put on” the player that when he leaves the BuildBattle, he becomes unmanageable until he re-logins? We’re suspecting the „Hide-players” settings but it does the same either on true or false.
Thanks for your reply!(módosítva)

## Error code
There is no specific error message...

## Additional info
- Spigot version: [16:57:54] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- Plugin version: All version.

**Comment by Plajer** [comment]
I'll add scoreboard saving to the inventory manager and this should solve your problem.

**Comment by Plajer** [comment]
Probably fixed in above commit, join our discord for pre-release jar if you want.

**Comment by iamharak** [comment]
Hello, where can i find a link to the .jar file? :D
I joined the Discord server but did not find the .jar file.

Plajer <notifications@github.com> ezt írta (időpont: 2018. júl. 30., H,
12:30):

**Comment by iamharak** [comment]
My Discord user: ScoterZ#6336

Máté Harák <mateharak01@gmail.com> ezt írta (időpont: 2018. aug. 1., Sze,
12:52):

**Comment by Plajer** [comment]
Message me

**Comment by Plajer** [comment]
Author received simple workaround method using rewards section via discord with no further response long time ago.
