### ISSUE TITLE
Named items can't be dropped even not in game.

### ISSUE THREAD

**Issue by RichVillage** [Plajer-Lair/BuildBattle#7]
### Sort description of issue
Named items can't be dropped even I am not running game.
My server have two contents, Free Creative and Build Battle.. but on Free Creative map, named items can't be dropped by keyboard "Q".
I disabled many plugins, and when I disabled Build Battle plugin, named items can be dropped.
I think I found the code error on your code, but I can't compile your code with it.. I don't have project file. If you can, would you please give me the project file and let me fix this problem...??

Sorry for my English again.

## Error code
```
No error code.
```

## Additional info
- Spigot version: spigot-1.12.2-R0.1-SNAPSHOT-b1648
- Plugin version: 3.4.1

**Comment by Plajer** [comment]
You don't need project file to compile plugin from GitHub sources.

**Comment by Plajer** [comment]
This bug will be fixed in upcoming update.

**Comment by Plajer** [comment]
Fixed in commit above, check out beta releases at our discord.

**Comment by RichVillage** [comment]
Thank you! Have a nice day...
